package com.richikin.enumslib;

public enum ScreenID
{
    _BASE_SCREEN,
    _MAIN_MENU,
    _SETTINGS_SCREEN,
    _CREDITS_SCREEN,
    _LOADING_SCREEN,
    _GAME_SCREEN,
    _EXIT_SCREEN,
    _HISCORE_SCREEN,
    _ACHIEVEMENTS_SCREEN,
    _STATS_SCREEN,
    _PRIVACY_POLICY_SCREEN,
    _TEST_PANEL,
    _DEVELOPER_PANEL,
    _END_GAME_SCREEN,
    _INSTRUCTIONS_SCREEN,

    _BASE_RENDERER,
    _TITLE_RENDERER,
    _GAME_RENDERER,

    _NO_ID
}
